### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by srikanth007m** [sidjay10/cstracer#2]
Dear @Anish-Saxena @sidjay10,

I am trying to build valgrind 3.19.0 with android-ndk-r23c toolchain. Applied all required patches mentioned in your project. I am landing into below issue during compilation. Any thoughts?

`/local/mnt/workspace/Android_ndk/android-ndk-r23c/toolchains/llvm/prebuilt/linux-x86_64//bin/aarch64-linux-android23-clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../include -I../include -I../VEX/pub -I../VEX/pub -DVGA_arm64=1 -DVGO_linux=1 -DVGP_arm64_linux=1 -DVGPV_arm64_linux_android=1  -I../coregrind -DVG_LIBDIR="\"/data/local/tmp/Inst/libexec/valgrind"\" -DVG_PLATFORM="\"arm64-linux\"" -DVGC_android_clang=1  -m64 -O2 -g -Wall -Wmissing-prototypes -Wshadow -Wpointer-arith -Wstrict-prototypes -Wmissing-declarations -Wcast-align -Wcast-qual -Wwrite-strings -Wempty-body -Wformat -Wformat-security -Wignored-qualifiers -Wenum-conversion -finline-functions -fno-stack-protector -fno-strict-aliasing -fno-builtin -Wno-cast-align -Wno-self-assign -Wno-tautological-compare  -DENABLE_LINUX_TICKET_LOCK -DVGC_android_clang=1 -MT libcoregrind_arm64_linux_a-m_commandline.o -MD -MP -MF .deps/libcoregrind_arm64_linux_a-m_commandline.Tpo -c -o libcoregrind_arm64_linux_a-m_commandline.o `test -f 'm_commandline.c' || echo './'`m_commandline.c
m_main.c:2625:28: warning: no previous prototype for function '__aeabi_memcpy4' [-Wmissing-prototypes]
__attribute__((weak)) void __aeabi_memcpy4() {}
                           ^
m_main.c:2625:23: note: declare 'static' if the function is not intended to be used outside of this translation unit
__attribute__((weak)) void __aeabi_memcpy4() {}
                      ^
                      static
m_main.c:2625:43: warning: this old-style function definition is not preceded by a prototype [-Wstrict-prototypes]
__attribute__((weak)) void __aeabi_memcpy4() {}
                                          ^
m_main.c:2626:28: warning: no previous prototype for function '__aeabi_memcpy8' [-Wmissing-prototypes]
__attribute__((weak)) void __aeabi_memcpy8() {}
                           ^
m_main.c:2626:23: note: declare 'static' if the function is not intended to be used outside of this translation unit
__attribute__((weak)) void __aeabi_memcpy8() {}
                      ^
                      static
m_main.c:2626:43: warning: this old-style function definition is not preceded by a prototype [-Wstrict-prototypes]
__attribute__((weak)) void __aeabi_memcpy8() {}
                                          ^
m_main.c:2627:28: warning: no previous prototype for function '__aeabi_memclr8' [-Wmissing-prototypes]
__attribute__((weak)) void __aeabi_memclr8() {}
                           ^
m_main.c:2627:23: note: declare 'static' if the function is not intended to be used outside of this translation unit
__attribute__((weak)) void __aeabi_memclr8() {}
                      ^
                      static
m_main.c:2627:43: warning: this old-style function definition is not preceded by a prototype [-Wstrict-prototypes]
__attribute__((weak)) void __aeabi_memclr8() {}
                                          ^
m_main.c:2662:7: error: conflicting types for '__aeabi_memcpy4'
void *__aeabi_memcpy4(void *dest, const void *src, SizeT n);
      ^
m_main.c:2625:28: note: previous definition is here
__attribute__((weak)) void __aeabi_memcpy4() {}
                           ^
m_main.c:2663:7: error: conflicting types for '__aeabi_memcpy4'
void *__aeabi_memcpy4(void *dest, const void *src, SizeT n)
      ^
m_main.c:2625:28: note: previous definition is here
__attribute__((weak)) void __aeabi_memcpy4() {}
                           ^
m_main.c:2668:7: error: conflicting types for '__aeabi_memcpy8'
void *__aeabi_memcpy8(void *dest, const void *src, SizeT n);
      ^
m_main.c:2626:28: note: previous definition is here
__attribute__((weak)) void __aeabi_memcpy8() {}
                           ^
m_main.c:2669:7: error: conflicting types for '__aeabi_memcpy8'
void *__aeabi_memcpy8(void *dest, const void *src, SizeT n)
      ^
m_main.c:2626:28: note: previous definition is here
__attribute__((weak)) void __aeabi_memcpy8() {}
                           ^
m_main.c:2687:7: error: conflicting types for '__aeabi_memclr8'
void *__aeabi_memclr8(void *dest, SizeT n);
      ^
m_main.c:2627:28: note: previous definition is here
__attribute__((weak)) void __aeabi_memclr8() {}
                           ^
m_main.c:2688:7: error: conflicting types for '__aeabi_memclr8'
void *__aeabi_memclr8(void *dest, SizeT n)
      ^
m_main.c:2627:28: note: previous definition is here
__attribute__((weak)) void __aeabi_memclr8() {}
                           ^
6 warnings and 6 errors generated.
Makefile:8806: recipe for target 'libnolto_coregrind_arm_linux_a-m_main.o' failed
make[3]: *** [libnolto_coregrind_arm_linux_a-m_main.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/libcoregrind_arm64_linux_a-m_addrinfo.Tpo .deps/libcoregrind_arm64_linux_a-m_addrinfo.Po
mv -f .deps/libcoregrind_arm64_linux_a-m_commandline.Tpo .deps/libcoregrind_arm64_linux_a-m_commandline.Po
mv -f .deps/libnolto_coregrind_arm64_linux_a-m_main.Tpo .deps/libnolto_coregrind_arm64_linux_a-m_main.Po
make[3]: Leaving directory '/local/mnt/workspace/valgrind/valgrind-3.19.0/coregrind'
Makefile:2085: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/local/mnt/workspace/valgrind/valgrind-3.19.0/coregrind'
Makefile:896: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/local/mnt/workspace/valgrind/valgrind-3.19.0'
Makefile:759: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by sidjay10** [comment]
Compiling valgrind with clang is quite problematic. Can you use android ndk-10 instead. The ndk10 used to support gcc. I have provided build scripts in the repo. Use the aarch64-ndk10 script.

That is what we were using for our builds.

**Comment by sidjay10** [comment]
You do not have to apply any of these patches to compile with gcc.

**Comment by srikanth007m** [comment]
But this is a quite old toolchain. I am using API 32 for my work.

**Comment by Anish-Saxena** [comment]
Our target API was < 29 as we needed an OEM Android build with execute-only memory disabled. Just FYI.
